# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

*
!pyproject.toml
!uv.lock
!sdk
!packages
!plugins/nemo-builder
**/.venv
**/node_modules
**/__pycache__
**/.pytest_cache
**/*.pyc
