// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/** Written by pyarrow with its default (snappy) codec, as Data Designer writes its batches. */
export const PARQUET = {
  /** `{ prompt: 'hi', expected: 'hi' }, { prompt: 'yo', expected: 'yo' }` */
  twoRows:
    'UEFSMRUEFRgVHEwVBBUAEgAADCwCAAAAaGkCAAAAeW8VABUSFRYsFQQVEBUGFQYcNgAoAnlvGAJoaRERAAAACSACAAAABAEBAwIVBBUYFRxMFQQVABIAAAwsAgAAAGhpAgAAAHlvFQAVEhUWLBUEFRAVBhUGHDYAKAJ5bxgCaGkREQAAAAkgAgAAAAQBAQMCFQQZPDUAGAZzY2hlbWEVBAAVDCUCGAZwcm9tcHQlAEwcAAAAFQwlAhgIZXhwZWN0ZWQlAEwcAAAAFgQZHBksJgAcFQwZNQAGEBkYBnByb21wdBUCFgQWhAEWjAEmQCYIHDYAKAJ5bxgCaGkREQAZLBUEFQAVAgAVABUQFQIAPBYIGQYZJgAEAAAAJgAcFQwZNQAGEBkYCGV4cGVjdGVkFQIWBBaEARaMASbMASaUARw2ACgCeW8YAmhpEREAGSwVBBUAFQIAFQAVEBUCADwWCBkGGSYABAAAABaIAhYEJggWmAIAGRwYDEFSUk9XOnNjaGVtYRjgAS8vLy8vNkFBQUFBUUFBQUFBQUFLQUF3QUJnQUZBQWdBQ2dBQUFBQUJCQUFNQUFBQUNBQUlBQUFBQkFBSUFBQUFCQUFBQUFJQUFBQkVBQUFBQkFBQUFOVC8vLzhBQUFFRkVBQUFBQndBQUFBRUFBQUFBQUFBQUFnQUFBQmxlSEJsWTNSbFpBQUFBQURJLy8vL0VBQVVBQWdBQmdBSEFBd0FBQUFRQUJBQUFBQUFBQUVGRUFBQUFCd0FBQUFFQUFBQUFBQUFBQVlBQUFCd2NtOXRjSFFBQUFRQUJBQUVBQUFBABggcGFycXVldC1jcHAtYXJyb3cgdmVyc2lvbiAyNC4wLjAZLBwAABwAAAADAgAAUEFSMQ==',
  /** A `prompt` column with no rows. */
  empty:
    'UEFSMRUEFQAVAkwVABUAEgAAABUEGSw1ABgGc2NoZW1hFQIAFQwlAhgGcHJvbXB0JQBMHAAAABYAGRwZHCYAHBUMGSUABhkYBnByb21wdBUCFgAWHBYeJgAmCCkcFQQVABUCAAAAFhwWACYIFh4AGRwYDEFSUk9XOnNjaGVtYRigAS8vLy8vM0FBQUFBUUFBQUFBQUFLQUF3QUJnQUZBQWdBQ2dBQUFBQUJCQUFNQUFBQUNBQUlBQUFBQkFBSUFBQUFCQUFBQUFFQUFBQVVBQUFBRUFBVUFBZ0FCZ0FIQUF3QUFBQVFBQkFBQUFBQUFBRUZFQUFBQUJ3QUFBQUVBQUFBQUFBQUFBWUFBQUJ3Y205dGNIUUFBQVFBQkFBRUFBQUEAGCBwYXJxdWV0LWNwcC1hcnJvdyB2ZXJzaW9uIDI0LjAuMBkcHAAAADgBAABQQVIx',
} as const;

export const parquetFile = (base64: string, name = 'batch_00000.parquet'): File =>
  new File([Uint8Array.from(atob(base64), (char) => char.charCodeAt(0))], name);
