{{/*
SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nemo-helix.platform-configmap" . }}
  labels:
    {{- include "nemo-helix.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ include "nemo-helix.calculatedConfig" . | nindent 4 }}
